// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentTrackerApp.Services;

#nullable disable

namespace StudentTrackerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027184437_MessagesMigration")]
    partial class MessagesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StudentTrackerApp.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadByReciever")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecieverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MessageDb");
                });

            modelBuilder.Entity("StudentTrackerApp.Models.StudentTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudentTeacherDb");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentId = 1,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("StudentTrackerApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserDb");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bobbyhill@etsu.edu",
                            FirstName = "Bobby",
                            LastName = "Hill",
                            Password = "Password",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 2,
                            Email = "johnteach@etsu.edu",
                            FirstName = "John",
                            LastName = "Teach",
                            Password = "Password",
                            UserType = "Teacher"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
